In [1]:
# Importing Module

import math

In [2]:
math.pi

3.141592653589793

In [3]:
math.e

2.718281828459045

In [4]:
math.inf

inf

In [5]:
math.ceil(7.8)

8

In [7]:
math.floor(7.6)

7

In [8]:
float_list = [0.1,0.1, 0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1]

In [9]:
# To have a precise value of the list the following finction can be used.
math.fsum(float_list)

1.0

In [10]:
sum(float_list)

0.9999999999999999

In [11]:
math.gcd(30, 20)

10

In [4]:
# Importing Numpy library

!pip install numpy

In [5]:
import numpy as np

In [8]:
some_list = [1,2,3,4,5,6,7]

type(some_list)

list

In [9]:
some_array = np.array(some_list)

some_array

array([1, 2, 3, 4, 5, 6, 7])

In [10]:
type(some_array)

numpy.ndarray

In [11]:
ones_array = np.ones(5)

ones_array

array([1., 1., 1., 1., 1.])

In [12]:
type(ones_array)

numpy.ndarray

In [13]:
range_array = np.arange(8)

range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
reshaped_array = range_array.reshape(2, 4)

reshaped_array

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
reshaped_array = range_array.reshape(4,2)

reshaped_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [17]:
random_array = np.random.random((4,5))

random_array

array([[0.50321699, 0.05633865, 0.19879636, 0.54728805, 0.88931045],
       [0.39807689, 0.19746972, 0.95578158, 0.27574266, 0.55124486],
       [0.62389624, 0.06379597, 0.93131902, 0.31611674, 0.25874306],
       [0.40743072, 0.46006045, 0.9913922 , 0.0376834 , 0.63598675]])

In [18]:
range_array

array([0, 1, 2, 3, 4, 5, 6, 7])

In [19]:
mean = np.mean(range_array)

mean

3.5

In [20]:
median = np.median(range_array)

median

3.5

In [22]:
var = np.var(range_array)

var

5.25

In [23]:
std = np.std(range_array)

std

2.29128784747792

In [24]:
!pip install pandas

In [25]:
import pandas as pd

In [26]:
df = pd.DataFrame({
    'name' : ['John', 'Alice', 'Bob', 'Elieen', 'Rob'],
    'gender' : ['Male', 'Female', 'Male', 'Female', 'Male'],
    'age' : [45,20,30,14,67]
})

In [27]:
df

name  gender  age
0    John    Male   45
1   Alice  Female   20
2     Bob    Male   30
3  Elieen  Female   14
4     Rob    Male   67

In [29]:
df.describe()

age
count   5.000000
mean   35.200000
std    21.300235
min    14.000000
25%    20.000000
50%    30.000000
75%    45.000000
max    67.000000

In [30]:
subset_df = df[['name', 'age']]

subset_df

name  age
0    John   45
1   Alice   20
2     Bob   30
3  Elieen   14
4     Rob   67

In [31]:
groupby_df = df.groupby(by='gender').count()

groupby_df

name  age
gender           
Female     2    2
Male       3    3

In [32]:
import os


In [33]:
os.environ

environ{'HOSTNAME': 'nbserver',
        'SHELL': '/bin/bash',
        'TERM': 'xterm-color',
        'MSI_ENDPOINT': 'http://localhost:25198/nb/api/nbsvc/oauth2/token',
        'http_proxy': 'http://webproxy:3128',
        'USER': 'nbuser',
        'LD_LIBRARY_PATH': '/usr/lib64/MRO-3.3.0/R-3.3.0/lib/R/lib:',
        'SUDO_USER': 'root',
        'AZURE_HTTP_USER_AGENT': 'AzureNotebooks/0.5.0',
        'JPY_PARENT_PID': '41',
        'USERNAME': 'nbuser',
        'MAIL': '/var/mail/nbuser',
        'PATH': '/home/nbuser/anaconda3_501/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/nbuser/.local/bin',
        'PWD': '/home/nbuser/library/code',
        'R_LIBS': '/home/nbuser/R:/usr/local/lib/R/site-library:/usr/lib/R/site-library:/usr/lib/R/library',
        'AZURE_NOTEBOOKS_SERVER_URL': 'http://localhost:25198/nb',
        'LANG': 'en_US.UTF-8',
        'NBUSER_ENV': 'yes',
        'https_proxy': 'http://webproxy:3128',
        'SUDO_COMM

In [34]:
os.environ['USER']

'nbuser'